### ISSUE TITLE
Update to OSCAT 3.33

### ISSUE THREAD

**Issue by massimo-pizzardi** [sagatowski/alltwincat.com-oscat-basic#1]
Hello I realized the Twincat Library from the last version of OSCAT Library
[oscat_basic_333_TWINCAT31.zip](https://github.com/sagatowski/alltwincat.com-oscat-basic/files/4348510/oscat_basic_333_TWINCAT31.zip)
Please let me know if is useful.

Thanks

Massimo

**Comment by massimo-pizzardi** [comment]
I think that nobody is looking at this release, but I want to upload the latest version 3.3.3 of Oscat Library, also network 121 and building 100.

[Oscat library for TwinCat.zip](https://github.com/sagatowski/alltwincat.com-oscat-basic/files/4668077/Oscat.library.for.TwinCat.zip)

Have a nice day

Massimo

**Comment by dfreiberger** [comment]
@sagatowski it looks like https://github.com/RWTH-EBC/AixOCAT has a copy of OSCAT that might be maintained, would it make sense to deprecate this repository or point users to https://github.com/RWTH-EBC/AixOCAT? I only came across the AixOCAT version when searching the oscat forums.

It'd be pretty cool to apply TcUnit to OSCAT, may help catch some of the bugs :) Maybe I'll give it a shot some time.

**Comment by sagatowski** [comment]
@dfreiberger Thanks for making me aware of this project. I've updated the readme and linked to the projects website.
